version: '3'
services:
  core-postgres:
    image: postgres:9.6.17-alpine
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=diamnet
    ports:
      - "5641:5641"
    command: ["-p", "5641"]
    volumes:
      - "core-db-data:/var/lib/postgresql/data"
    network_mode: '${NETWORK_MODE:-bridge}'

  core:
    # to use a specific version of diamnet core
    # image: diamnet/diamnet-core:$VERSION
    image: diamnet/diamnet-core
    depends_on:
      - core-postgres
    restart: on-failure
    ports:
      - "11625:11625"
      - "11626:11626"
    command: /start
    volumes:
      - ./diamnet-core-testnet.cfg:/diamnet-core.cfg
      - ./core-start.sh:/start
    network_mode: '${NETWORK_MODE:-bridge}'

  aurora-postgres:
    image: postgres:9.6.17-alpine
    restart: on-failure
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=aurora
    ports:
      - "5432:5432"
    volumes:
      - "aurora-db-data:/var/lib/postgresql/data"
    network_mode: '${NETWORK_MODE:-bridge}'

  aurora:
    depends_on:
      - aurora-postgres
      - core
    build:
      # set build context to the root directory of the go monorepo
      context: ../../../
      dockerfile: services/aurora/docker/Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres@host.docker.internal:5432/aurora?sslmode=disable
      - DIAMNET_CORE_DATABASE_URL=postgres://postgres:mysecretpassword@host.docker.internal:5641/diamnet?sslmode=disable
      - HISTORY_ARCHIVE_URLS=https://history.diamnet.org/prd/core-testnet/core_testnet_001
      - NETWORK_PASSPHRASE=Test SDF Network ; September 2015
      - DIAMNET_CORE_URL=http://host.docker.internal:11626
      - INGEST=true
      - PER_HOUR_RATE_LIMIT=0
    network_mode: '${NETWORK_MODE:-bridge}'
    command: ["--apply-migrations"]

volumes:
  core-db-data:
  aurora-db-data:
